# Generated by Django 5.2.8 on 2026-02-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_estimates', '0030_shoppinglist_execution_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListBulkImport',
            fields=[
            ],
            options={
                'verbose_name': 'Shopping List',
                'verbose_name_plural': 'Shopping List',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client_estimates.shoppinglist',),
        ),
    ]
