# Generated by Django 5.1.14 on 2025-11-18 21:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatererAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('default_currency', models.CharField(choices=[('ILS', 'Israeli Shekel'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='ILS', max_length=3)),
                ('default_food_markup', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('staff_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8)),
                ('staff_tip_per_waiter', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=8)),
                ('real_dishes_price_per_person', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=8)),
                ('real_dishes_flat_fee', models.DecimalField(decimal_places=2, default=Decimal('400.00'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caterer',
                'verbose_name_plural': 'Caterers',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('event_location', models.CharField(blank=True, max_length=255)),
                ('guest_count', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(choices=[('ILS', 'Israeli Shekel'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='ILS', max_length=3)),
                ('include_premium_plastic', models.BooleanField(default=True)),
                ('include_premium_tablecloths', models.BooleanField(default=True)),
                ('wants_real_dishes', models.BooleanField(default=False)),
                ('real_dishes_price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('real_dishes_flat_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('staff_hours', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=5)),
                ('extra_waiters', models.PositiveIntegerField(default=0)),
                ('staff_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('staff_tip_per_waiter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('food_price_per_person', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('extras_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('staff_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('dishes_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_30_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes_internal', models.TextField(blank=True)),
                ('notes_for_customer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='client_estimates.catereraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('DECOR', 'Decor'), ('RENTAL', 'Rental'), ('SERVICE', 'Service'), ('OTHER', 'Other')], default='RENTAL', max_length=20)),
                ('charge_type', models.CharField(choices=[('PER_EVENT', 'Per event'), ('PER_PERSON', 'Per person')], default='PER_EVENT', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Internal cost', max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, help_text='Customer price (per person or per event, depending on charge type)', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='client_estimates.catereraccount')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('override_price', models.DecimalField(blank=True, decimal_places=2, help_text='If set, replaces automatic price calculation', max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_lines', to='client_estimates.estimate')),
                ('extra_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_lines', to='client_estimates.extraitem')),
            ],
            options={
                'verbose_name': 'Extra line',
                'verbose_name_plural': 'Extra lines',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='client_estimates.catereraccount')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cost_per_serving', models.DecimalField(decimal_places=2, max_digits=8)),
                ('markup', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('default_servings_per_person', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='client_estimates.menucategory')),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='client_estimates.catereraccount')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateFoodChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=True)),
                ('servings_per_person', models.DecimalField(blank=True, decimal_places=2, help_text="If blank, uses menu item's default", max_digits=5, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_choices', to='client_estimates.estimate')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_choices', to='client_estimates.menuitem')),
            ],
            options={
                'unique_together': {('estimate', 'menu_item')},
            },
        ),
    ]
