# Generated by Django 5.1.14 on 2025-11-18 21:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catereraccount',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The Django user who owns this catering business.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caterer_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estimateextraitem',
            name='override_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimatefoodchoice',
            name='servings_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='extraitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='extraitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
