# Generated by Django 5.1.14 on 2025-11-18 22:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0002_catereraccount_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateextraitem',
            name='override_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, replaces automatic price calculation', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimatefoodchoice',
            name='servings_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="If blank, uses menu item's default", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='extraitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Internal cost', max_digits=8),
        ),
        migrations.AlterField(
            model_name='extraitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Customer price (per person or per event, depending on charge type)', max_digits=8),
        ),
        migrations.CreateModel(
            name='MenuTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='client_estimates.catereraccount')),
                ('items', models.ManyToManyField(related_name='templates', to='client_estimates.menuitem')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('caterer', 'name')},
            },
        ),
    ]
