# Generated by Django 5.1.14 on 2025-11-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0003_alter_estimateextraitem_override_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='contract_terms',
            field=models.TextField(blank=True, default='By approving this estimate you confirm the event details listed above and agree to remit a 30% deposit to reserve the date. The remaining balance is due five (5) days before the event unless otherwise noted in writing. Any changes to guest counts, rentals, or services must be confirmed in writing. The client is responsible for venue access, utilities, and permits. Payment signifies acceptance of these terms.', help_text='Terms + conditions shown at the bottom of the summary/PDF.'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='is_invoice',
            field=models.BooleanField(default=False, help_text='Set automatically when the quote is converted into an invoice.'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='Shown on invoices and PDF downloads so clients know how to pay.'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='signature_date',
            field=models.DateField(blank=True, help_text='Date the estimate or invoice was accepted.', null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='signature_name',
            field=models.CharField(blank=True, help_text='Name of the person signing/approving the estimate.', max_length=200),
        ),
        migrations.AddField(
            model_name='estimate',
            name='signature_title',
            field=models.CharField(blank=True, help_text='Optional title to show under the signature line.', max_length=200),
        ),
        migrations.AddField(
            model_name='estimate',
            name='terms_acknowledged',
            field=models.BooleanField(default=False, help_text='Check when the client has acknowledged the contract terms.'),
        ),
    ]
