# Generated by Django 5.1.14 on 2025-11-19 07:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0004_estimate_contract_terms_estimate_is_invoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='deposit_30_percent',
            new_name='deposit_amount',
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='bank_details',
            field=models.TextField(blank=True, help_text='Wire / bank instructions that appear on estimates and invoices.'),
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='brand_accent_color',
            field=models.CharField(default='#b08c6d', help_text='Accent color used for highlights and cards.', max_length=7),
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='brand_logo',
            field=models.FileField(blank=True, null=True, upload_to='caterer_logos/'),
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='brand_primary_color',
            field=models.CharField(default='#0f172a', help_text='Primary accent color for PDF headings.', max_length=7),
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='default_payment_terms',
            field=models.TextField(blank=True, default='30% deposit due upon acceptance to reserve date. Remaining balance due on the event date unless alternate arrangements are approved in writing.', help_text='Shown on new estimates unless overridden.'),
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='document_background',
            field=models.CharField(choices=[('CLEAN', 'Clean white'), ('WATERCOLOR_SAGE', 'Watercolor sage'), ('WATERCOLOR_ROSE', 'Blush watercolor'), ('TEXTURED_STONE', 'Textured stone')], default='CLEAN', max_length=30),
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='document_font_family',
            field=models.CharField(choices=[('SERIF', 'Classic serif'), ('SANS', 'Modern sans')], default='SANS', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Deposit due'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='deposit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Used to calculate deposit in the PDF summary.', max_digits=5),
        ),
        migrations.AddField(
            model_name='estimate',
            name='meal_plan',
            field=models.JSONField(blank=True, default=list, help_text='List of meal names (e.g. Friday Dinner, Shabbos Lunch) used to organize menu selections.'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='is_ala_carte',
            field=models.BooleanField(default=False, help_text='Skip staff/dishes/plastic info – food delivery only (a la carte).'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Bank transfer'), ('CASH', 'Cash'), ('CREDIT_CARD', 'Credit card'), ('CHECK', 'Check')], help_text='Primary payment method for this document.', max_length=30),
        ),
        migrations.AddField(
            model_name='estimate',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='High-level schedule (e.g. deposit %, final due date).'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='contract_terms',
            field=models.TextField(blank=True, default='By approving this estimate you confirm the event details listed above and agree to remit the deposit listed in the summary to reserve the date. The remaining balance is due five (5) days before the event unless otherwise noted in writing. Any changes to guest counts, rentals, or services must be confirmed in writing. The client is responsible for venue access, utilities, and permits. Payment signifies acceptance of these terms.', help_text='Terms + conditions shown at the bottom of the summary/PDF.'),
        ),
        migrations.AddField(
            model_name='estimatefoodchoice',
            name='meal_name',
            field=models.CharField(blank=True, help_text='Optional meal label (e.g. Friday Dinner) for multi-meal estimates.', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='estimatefoodchoice',
            unique_together={('estimate', 'menu_item', 'meal_name')},
        ),
    ]
