# Generated by Django 5.1.14 on 2025-11-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0006_estimate_meal_plan_estimatefoodchoice_meal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='catereraccount',
            name='document_surface_style',
            field=models.CharField(choices=[('CARD', 'Elevated white cards'), ('TRANSPARENT', 'Transparent over background')], default='CARD', help_text='Control whether PDFs use floating cards or transparent sections.', max_length=20),
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='estimate_number_counter',
            field=models.PositiveIntegerField(default=1000, help_text='Next estimate/invoice number to issue.'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_number',
            field=models.PositiveIntegerField(blank=True, help_text='Sequential estimate/invoice number for client-facing docs.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('caterer', 'estimate_number')},
        ),
    ]
