# Generated by Django 5.2.8 on 2025-11-20 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0007_catereraccount_document_surface_style_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catereraccount',
            options={'verbose_name': 'Company profile', 'verbose_name_plural': 'Company profiles'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Menu categories'},
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='dashboard_banner_end',
            field=models.DateTimeField(blank=True, help_text='Optional end datetime for the dashboard message.', null=True),
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='dashboard_banner_message',
            field=models.TextField(blank=True, help_text='Message shown on the dashboard. Leave blank when you have nothing to announce.'),
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='dashboard_banner_start',
            field=models.DateTimeField(blank=True, help_text='Optional start datetime for the dashboard message.', null=True),
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='primary_contact_name',
            field=models.CharField(blank=True, help_text='Name used for greetings and dashboard personalization.', max_length=200),
        ),
        migrations.AlterField(
            model_name='catereraccount',
            name='document_background',
            field=models.CharField(choices=[('CLEAN', 'Clean white'), ('WATERCOLOR_SAGE', 'Watercolor sage wash'), ('WATERCOLOR_ROSE', 'Blush watercolor wash'), ('TEXTURED_STONE', 'Textured stone wash'), ('STENCIL_EUCALYPTUS', 'Eucalyptus stencil (greens)'), ('STENCIL_BLUSH', 'Blush bloom stencil'), ('STENCIL_MARBLE', 'Marble stencil'), ('STENCIL_BOTANICAL', 'Botanical parchment stencil'), ('STENCIL_WOODLAND', 'Rustic board stencil')], default='CLEAN', max_length=30),
        ),
        migrations.CreateModel(
            name='ClientInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('preferred_contact_method', models.CharField(blank=True, max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('converted_to_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='client_estimates.catereraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatererTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='client_estimates.catereraccount')),
                ('related_inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='client_estimates.clientinquiry')),
            ],
            options={
                'ordering': ['completed', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='client_estimates.catereraccount')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('caterer', 'email', 'phone')},
            },
        ),
    ]
