# Generated by Django 5.2.8 on 2025-11-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0008_alter_catereraccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catereraccount',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used for public inquiry links. Example: palatecatering', null=True, unique=True),
        ),
    ]
