# Generated by Django 5.2.8 on 2025-11-27 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0010_estimate_manual_meal_totals'),
    ]

    operations = [
        migrations.CreateModel(
            name='TastingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('appointment_type', models.CharField(choices=[('TASTING', 'Tasting'), ('MEETING', 'Meeting')], default='TASTING', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='SCHEDULED', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='client_estimates.catereraccount')),
                ('estimate', models.ForeignKey(blank=True, help_text='Optional link to an estimate so client info stays in sync.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='client_estimates.estimate')),
            ],
            options={
                'verbose_name': 'Tasting / meeting',
                'verbose_name_plural': 'Tastings / meetings',
                'ordering': ['start_at'],
            },
        ),
    ]
