# Generated by Django 5.2.8 on 2025-11-27 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0012_trialrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='catereraccount',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catereraccount',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrialPaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Payment link to restart after trial.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caterer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial_payment_link', to='client_estimates.catereraccount')),
            ],
        ),
    ]
