# Generated by Django 5.2.8 on 2025-12-23 20:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0016_estimate_meal_guest_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='meal_service_details',
            field=models.JSONField(blank=True, default=dict, help_text='Optional per-meal overrides for staffing and dish rentals.'),
        ),
        migrations.AlterField(
            model_name='catereraccount',
            name='real_dishes_flat_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('400.00'), help_text='Flat delivery / dishes fee applied once when real dishes are requested.', max_digits=8, verbose_name='Delivery fee'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='real_dishes_flat_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat delivery / dishes fee applied once when real dishes are requested.', max_digits=8, null=True, verbose_name='Delivery fee'),
        ),
    ]
