# Generated by Django 5.2.8 on 2025-12-24 21:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0017_estimate_meal_service_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='kids_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Discount applied to kids when no kids menu is used (e.g., kids eat adult menu at a reduced rate).', max_digits=5),
        ),
    ]
