# Generated by Django 5.2.8 on 2025-12-28 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0018_estimate_kids_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='plasticware_color',
            field=models.CharField(blank=True, help_text='Chad Paami color choice when using disposables.', max_length=200),
        ),
        migrations.AddField(
            model_name='estimate',
            name='tablecloth_details',
            field=models.JSONField(blank=True, default=dict, help_text='Optional per-meal tablecloth notes and charges.'),
        ),
        migrations.CreateModel(
            name='PlasticwareOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plasticware_options', to='client_estimates.catereraccount')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('caterer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TableclothOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablecloth_options', to='client_estimates.catereraccount')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('caterer', 'name')},
            },
        ),
    ]
