# Generated by Django 5.2.8 on 2025-12-28 10:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0019_estimate_plasticware_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='deposit_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount actually received toward this estimate/invoice.', max_digits=12),
        ),
    ]
