# Generated by Django 5.2.8 on 2026-01-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0020_estimate_deposit_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='sort_order_override',
            field=models.PositiveIntegerField(blank=True, help_text='Optional. Lower numbers appear before alphabetized items.', null=True),
        ),
    ]
