# Generated by Django 5.2.8 on 2026-01-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_estimates", "0021_menuitem_sort_order_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="estimate_type",
            field=models.CharField(
                choices=[("STANDARD", "Standard"), ("KIDDUSH", "Kiddush")],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="menu_type",
            field=models.CharField(
                choices=[("STANDARD", "Standard"), ("KIDDUSH", "Kiddush")],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="menutemplate",
            name="menu_type",
            field=models.CharField(
                choices=[("STANDARD", "Standard"), ("KIDDUSH", "Kiddush")],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="menutemplate",
            unique_together={("caterer", "name", "menu_type")},
        ),
    ]
