# Generated by Django 5.2.8 on 2026-01-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_estimates", "0022_kiddush_estimate_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="staff_count_override",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional: override the total staff count and ignore automatic calculation.",
                null=True,
            ),
        ),
    ]
