# Generated by Django 5.2.8 on 2026-02-14 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0023_estimate_staff_count_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KiddushEstimate',
            fields=[
            ],
            options={
                'verbose_name': 'Kiddush estimate',
                'verbose_name_plural': 'Kiddush estimates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client_estimates.estimate',),
        ),
        migrations.CreateModel(
            name='EstimateExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.FileField(upload_to='estimate_expenses/receipts/%Y/%m/%d/')),
                ('voice_note', models.FileField(upload_to='estimate_expenses/voice_notes/%Y/%m/%d/')),
                ('voice_note_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('note_text', models.TextField(blank=True, help_text='Internal note/transcript for the voice recording.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_expense_entries', to=settings.AUTH_USER_MODEL)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_entries', to='client_estimates.estimate')),
            ],
            options={
                'verbose_name': 'Estimate expense entry',
                'verbose_name_plural': 'Estimate expense entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='XpenzMobileToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xpenz_mobile_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xpenz mobile token',
                'verbose_name_plural': 'Xpenz mobile tokens',
            },
        ),
    ]
