# Generated by Django 5.2.8 on 2026-02-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0024_kiddushestimate_estimateexpenseentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateexpenseentry',
            name='expense_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estimateexpenseentry',
            name='expense_text',
            field=models.CharField(blank=True, help_text='Short expense line item (e.g. vegetables, gas, waiter tip).', max_length=255),
        ),
        migrations.AddField(
            model_name='estimateexpenseentry',
            name='is_manual_only',
            field=models.BooleanField(default=False, help_text='True when the entry was added manually without receipt/audio files.'),
        ),
        migrations.AlterField(
            model_name='estimateexpenseentry',
            name='receipt_image',
            field=models.FileField(blank=True, null=True, upload_to='estimate_expenses/receipts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='estimateexpenseentry',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='estimate_expenses/voice_notes/%Y/%m/%d/'),
        ),
    ]
