# Generated by Django 5.2.8 on 2026-02-15 22:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0025_estimateexpenseentry_expense_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateStaffTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('KITCHEN', 'Kitchen Staff'), ('WAIT', 'Wait Staff'), ('MANAGEMENT', 'Management Staff')], max_length=20)),
                ('worker_first_name', models.CharField(max_length=120)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('punched_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('punched_out_at', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('applied_to_expenses', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_time_entries_created', to=settings.AUTH_USER_MODEL)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_time_entries', to='client_estimates.estimate')),
                ('expense_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_time_entries', to='client_estimates.estimateexpenseentry')),
            ],
            options={
                'verbose_name': 'Estimate staff time entry',
                'verbose_name_plural': 'Estimate staff time entries',
                'ordering': ['-punched_in_at'],
            },
        ),
        migrations.CreateModel(
            name='CatererUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_mobile_app', models.BooleanField(default=True)),
                ('can_add_expenses', models.BooleanField(default=True)),
                ('can_view_job_billing', models.BooleanField(default=False)),
                ('can_manage_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='client_estimates.catereraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caterer_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caterer user access',
                'verbose_name_plural': 'Caterer user access',
                'ordering': ['caterer__name', 'user__username'],
                'unique_together': {('caterer', 'user')},
            },
        ),
    ]
