# Generated by Django 5.2.8 on 2026-02-17 15:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0026_estimatestafftimeentry_catereruseraccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='client_estimates.catereraccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_lists_created', to=settings.AUTH_USER_MODEL)),
                ('estimate', models.ForeignKey(blank=True, help_text='Optional estimate reference used for context only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_lists', to='client_estimates.estimate')),
            ],
            options={
                'verbose_name': 'Shopping list',
                'verbose_name_plural': 'Shopping lists',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(blank=True, help_text='Optional variant, e.g. pack size, dry/fresh, jar, etc.', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('category', models.CharField(choices=[('PRODUCE', 'Produce'), ('MEAT_POULTRY_FISH', 'Meat / Poultry / Fish'), ('DAIRY_EGGS', 'Dairy / Eggs'), ('PANTRY', 'Pantry'), ('BAKERY', 'Bakery'), ('FROZEN', 'Frozen'), ('BEVERAGES', 'Beverages'), ('DISPOSABLES', 'Disposables'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_items_created', to=settings.AUTH_USER_MODEL)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='client_estimates.shoppinglist')),
            ],
            options={
                'verbose_name': 'Shopping list item',
                'verbose_name_plural': 'Shopping list items',
                'ordering': ['category', 'item_name', 'item_type', 'created_at'],
            },
        ),
    ]
