# Generated by Django 5.2.8 on 2026-02-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0027_shoppinglist_shoppinglistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={'ordering': ['is_completed', 'category', 'item_name', 'item_type', 'created_at'], 'verbose_name': 'Shopping list item', 'verbose_name_plural': 'Shopping list items'},
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Checked off/purchased on a shopping run.'),
        ),
    ]
