# Generated by Django 5.2.8 on 2026-02-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0028_alter_shoppinglistitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={'ordering': ['is_completed', 'category', 'item_name', 'item_type', 'item_unit', 'created_at'], 'verbose_name': 'Shopping list item', 'verbose_name_plural': 'Shopping list items'},
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='item_unit',
            field=models.CharField(blank=True, help_text='Optional quantity unit, e.g. Kg, Pieces, Cans.', max_length=60),
        ),
    ]
