# Generated by Django 5.2.8 on 2026-02-17 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0029_alter_shoppinglistitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='execution_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='execution_started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_lists_execution_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='collaboration_note',
            field=models.CharField(blank=True, choices=[('', 'None'), ('COMBINED', 'Combined'), ('ADDED', 'Added')], default='', help_text='Collaboration marker shown during shared list execution.', max_length=20),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_items_completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
