# Generated by Django 5.2.8 on 2026-02-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0030_shoppinglist_execution_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete marker. Keeps historical items for catalog memory.', null=True),
        ),
    ]
