# Generated by Django 5.2.8 on 2026-03-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0031_shoppinglist_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='client_tipped_at_event',
            field=models.BooleanField(default=False, help_text='Exclude suggested waiter tip from totals when client tips directly at the event.'),
        ),
    ]
