# Generated by Django 5.2.8 on 2026-03-18 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0032_estimate_client_tipped_at_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xpenzmobiletoken',
            options={'verbose_name': 'X Planner mobile token', 'verbose_name_plural': 'X Planner mobile tokens'},
        ),
        migrations.CreateModel(
            name='EstimatePlannerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('DECOR', 'Decor'), ('RENTALS', 'Rentals'), ('ORDERS', 'Orders'), ('SPECIAL_REQUESTS', 'Special Requests'), ('PRINTING', 'Printing'), ('STAFFING', 'Staffing')], default='DECOR', max_length=30)),
                ('group_code', models.CharField(blank=True, help_text='Planner subgroup code (e.g. table_cloths, furniture).', max_length=80)),
                ('item_code', models.CharField(blank=True, help_text='Optional item type code inside a subgroup (e.g. floral, chairs).', max_length=80)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Field-value payload for this planner line.')),
                ('notes', models.TextField(blank=True)),
                ('is_checked', models.BooleanField(default=False, help_text='Checklist marker used in planning board and PDFs.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_entries', to='client_estimates.catereraccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_entries_created', to=settings.AUTH_USER_MODEL)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_entries', to='client_estimates.estimate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_entries_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estimate planner entry',
                'verbose_name_plural': 'Estimate planner entries',
                'ordering': ['section', 'sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannerFieldMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('DECOR', 'Decor'), ('RENTALS', 'Rentals'), ('ORDERS', 'Orders'), ('SPECIAL_REQUESTS', 'Special Requests'), ('PRINTING', 'Printing'), ('STAFFING', 'Staffing')], default='DECOR', max_length=30)),
                ('group_code', models.CharField(blank=True, max_length=80)),
                ('item_code', models.CharField(blank=True, max_length=80)),
                ('field_code', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=255)),
                ('value_key', models.CharField(db_index=True, max_length=255)),
                ('usage_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_field_memory', to='client_estimates.catereraccount')),
            ],
            options={
                'verbose_name': 'Planner field memory',
                'verbose_name_plural': 'Planner field memory',
                'ordering': ['section', 'group_code', 'item_code', 'field_code', 'value'],
                'unique_together': {('caterer', 'section', 'group_code', 'item_code', 'field_code', 'value_key')},
            },
        ),
    ]
