# Generated by Django 5.2.8 on 2026-06-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0036_planneroptioncard'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='wait_staff_instructions',
            field=models.TextField(blank=True, help_text='Instructions printed on the Wait Staff Workflow sheet.'),
        ),
    ]
