# Generated by Django 5.2.8 on 2026-07-08 10:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0037_menuitem_wait_staff_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional intro text shown at the top of the customer menu.')),
                ('price_per_person', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed base price per guest. Premium item surcharges are added on top of this.', max_digits=10)),
                ('menu_type', models.CharField(choices=[('STANDARD', 'Standard'), ('KIDDUSH', 'Kiddush')], default='STANDARD', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_menus', to='client_estimates.catereraccount')),
            ],
            options={
                'verbose_name': 'Preset menu',
                'verbose_name_plural': 'Preset menus',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='estimate',
            name='preset_menu',
            field=models.ForeignKey(blank=True, help_text='If set, this estimate was built from a preset / choice menu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='client_estimates.presetmenu'),
        ),
        migrations.CreateModel(
            name='PresetMenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('selection_label', models.CharField(blank=True, help_text="Printed instruction, e.g. 'Choose 3' or 'Pick one (or none)'. Auto-derived from the pick counts if left blank.", max_length=120)),
                ('min_choices', models.PositiveIntegerField(default=0, help_text='Fewest options the customer must pick (0 = optional).')),
                ('max_choices', models.PositiveIntegerField(default=1, help_text='Most options the customer may pick.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('preset_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='client_estimates.presetmenu')),
            ],
            options={
                'verbose_name': 'Preset menu category',
                'verbose_name_plural': 'Preset menu categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PresetMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surcharge_per_person', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra charge per guest when this premium option is chosen. Leave 0 for included items.', max_digits=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='client_estimates.presetmenucategory')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_uses', to='client_estimates.menuitem')),
            ],
            options={
                'verbose_name': 'Preset menu item',
                'verbose_name_plural': 'Preset menu items',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
