# Generated by Django 5.2.8 on 2026-07-09 21:07

import django.db.models.deletion
from django.db import migrations, models


def backfill_preset_menu(apps, schema_editor):
    PresetMenuItem = apps.get_model('client_estimates', 'PresetMenuItem')
    for pmi in PresetMenuItem.objects.select_related('category').all():
        if pmi.category_id and not pmi.preset_menu_id:
            pmi.preset_menu_id = pmi.category.preset_menu_id
            pmi.save(update_fields=['preset_menu'])


class Migration(migrations.Migration):

    dependencies = [
        ('client_estimates', '0038_presetmenu_estimate_preset_menu_presetmenucategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetmenuitem',
            name='preset_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='client_estimates.presetmenu'),
        ),
        migrations.RunPython(backfill_preset_menu, migrations.RunPython.noop),
    ]
