# Generated by Django 5.2.8 on 2026-02-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_estimates', '0026_estimatestafftimeentry_catereruseraccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
            ],
            options={
                'verbose_name': 'App User',
                'verbose_name_plural': 'App Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client_estimates.catereruseraccess',),
        ),
    ]
